
- name: Install Alloy
  ansible.builtin.include_role:
    name: grafana.grafana.alloy
  vars:
    alloy_config: |
      logging {
        level  = "info"
        format = "logfmt"
      }
      
      loki.write "to_loki" {
        endpoint {
          url = "http://192.168.0.51:3100/loki/api/v1/push"
        }
      }

      // __journal__* -> echte Loki-Labels machen
      loki.relabel "journal" {
        forward_to = []

        rule {
          source_labels = ["__journal__systemd_unit"]
          target_label  = "unit"
        }
      }

      loki.source.journal "systemd" {
        forward_to    = [loki.write.to_loki.receiver]
        relabel_rules = loki.relabel.journal.rules

        // echte Labels (werden in Loki gespeichert!)
        labels = {
          job    = "systemd-journal",
          host   = constants.hostname,
          source = "journal",
        }

      }

            
      local.file_match "local_files" {
        path_targets = [
          { __path__ = "/var/log/*.log" },
          { __path__ = "/var/log/nginx/*.log" },
        ]
      }

      loki.source.file "log_scrape" {
        targets    = local.file_match.local_files.targets
        forward_to = [loki.write.to_loki.receiver]
        tail_from_end = true
      }