

- import_tasks: epal.yml  
  when: ansible_distribution == "OracleLinux"

- name: Installiere chrony + fail2ban + htop
  ansible.builtin.package:
    name: 
      - chrony
      - fail2ban
      - htop
      - moreutils
    state: present
    update_cache: true

- import_tasks: alloy.yml  





