- name: Install prerequisites (Debian/Ubuntu)
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: OS-specific 
  debug:
    msg: "Installation auf {{ ansible_os_family }}."

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

- name: Add user to docker group
  ansible.builtin.user:
    name: "martin"
    groups: docker
    append: true

- import_tasks: busybox_container.yml      
- import_tasks: portainer-edge_agent.yml      
