all:
  children:
    dockersrv:
      hosts:
        docker-01:
          ansible_host: 192.168.0.250
        docker-02:
          ansible_host: 192.168.0.59

    ubuntu22:
      hosts:
        docker-01:
          ansible_host: 192.168.0.250

    rhel10:
      hosts:
        docker-02:
          ansible_host: 192.168.0.59                