all:
  children:
    dockersrv:
      hosts:
        docker-01:
          ansible_host: 192.168.0.250
        docker-02:
          ansible_host: 192.168.0.59

    cis_ubuntu24:
      hosts:
        docker-01:
          ansible_host: 192.168.0.250            